services:
  webapp:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_NAME: notesdb
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin

  database:
    image: postgres
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
